read_verilog -sv $lib_dir/dsp_add.v
read_verilog -sv $lib_dir/dsp_add_v2.v
read_verilog -sv $lib_dir/dsp_add_v4.v
read_verilog -sv $lib_dir/dsp_add_v3.v
read_verilog -sv $lib_dir/dsp_mul.v
read_verilog -sv $lib_dir/dsp_sub.v
read_verilog -sv $lib_dir/dsp_sub_v2.v
read_verilog -sv $lib_dir/dsp_sub_v4.v
read_verilog -sv $lib_dir/dsp_sub_v3.v
read_verilog -sv $lib_dir/dsp_and.v
read_verilog -sv $lib_dir/dsp_or.v
read_verilog -sv $lib_dir/dsp_xor.v
read_verilog -sv $lib_dir/dsp_nor.v
read_verilog -sv $lib_dir/dsp_xnor.v
read_verilog -sv $lib_dir/dsp_nand.v
read_verilog -sv $lib_dir/dsp_not.v
read_verilog -sv $lib_dir/lut_add_w8.v
read_verilog -sv $lib_dir/lut_sub_w8.v
read_verilog -sv $lib_dir/lut_add_w16.v
read_verilog -sv $lib_dir/lut_sub_w16.v
read_verilog -sv $lib_dir/lut_add_w32.v
read_verilog -sv $lib_dir/lut_sub_w32.v
read_verilog -sv $lib_dir/dsp_add_mul.v
read_verilog -sv $lib_dir/dsp_add_reg_mul.v
read_verilog -sv $lib_dir/dsp_add_add_add_mul.v
read_verilog -sv $lib_dir/lut_eq_b_i8_i8.v
