${XILINX_VIVADO}/data/verilog/src/glbl.v
${LIB_DIR}/test.v
${LIB_DIR}/dsp_add.v
${LIB_DIR}/dsp_add_v2.v
${LIB_DIR}/dsp_add_v4.v
${LIB_DIR}/dsp_add_v3.v
${LIB_DIR}/dsp_mul.v
${LIB_DIR}/dsp_sub.v
${LIB_DIR}/dsp_sub_v2.v
${LIB_DIR}/dsp_sub_v4.v
${LIB_DIR}/dsp_sub_v3.v
${LIB_DIR}/dsp_and.v
${LIB_DIR}/dsp_or.v
${LIB_DIR}/dsp_xor.v
${LIB_DIR}/dsp_nor.v
${LIB_DIR}/dsp_xnor.v
${LIB_DIR}/dsp_nand.v
${LIB_DIR}/dsp_not.v
${LIB_DIR}/lut_add_w8.v
${LIB_DIR}/lut_sub_w8.v
${LIB_DIR}/lut_add_w16.v
${LIB_DIR}/lut_sub_w16.v
${LIB_DIR}/lut_add_w32.v
${LIB_DIR}/lut_sub_w32.v
${LIB_DIR}/dsp_add_mul.v
${LIB_DIR}/dsp_add_reg_mul.v
${LIB_DIR}/dsp_add_add_add_mul.v
${LIB_DIR}/lut_eq_b_i8_i8.v
