FROM ubuntu:18.04

ARG USER_ID
ARG VIVADO_BIN

ENV USERNAME=vivado

RUN apt-get update --fix-missing

COPY ${VIVADO_BIN} /tmp/
COPY auth.sh /tmp/

RUN /tmp/${VIVADO_BIN} --keep --noexec --target /tmp/wi

RUN adduser --disabled-password --gecos '' --uid ${USER_ID} ${USERNAME}
USER ${USERNAME}
