${XILINX_VIVADO}/data/verilog/src/glbl.v
${VERILOG_DIR}/add_i8_i8_i8.v
${VERILOG_DIR}/sub_i8_i8_i8.v
${VERILOG_DIR}/add_i8v4_i8v4_i8v4.v
${VERILOG_DIR}/sub_i8v4_i8v4_i8v4.v
${VERILOG_DIR}/add_mul_i8_i8_i8_i8.v
${VERILOG_DIR}/add_reg_mul_i8_i8_i8_b_i8.v
${VERILOG_DIR}/mul_i8_i8_i8.v
${VERILOG_DIR}/and_i8_i8_i8.v
${VERILOG_DIR}/id_i8_i8.v
${VERILOG_DIR}/nor_i8_i8_i8.v
${VERILOG_DIR}/not_i8_i8.v
${VERILOG_DIR}/or_i8_i8_i8.v
${VERILOG_DIR}/xnor_i8_i8_i8.v
${VERILOG_DIR}/xor_i8_i8_i8.v
${VERILOG_DIR}/and_b_b_b.v
${VERILOG_DIR}/const_i8.v
${VERILOG_DIR}/dsp_add_i8_i8_i8.v
${VERILOG_DIR}/dsp_and_i8_i8_i8.v
${VERILOG_DIR}/dsp_or_i8_i8_i8.v
${VERILOG_DIR}/dsp_sub_i8_i8_i8.v
${VERILOG_DIR}/eq_b_b_b.v
${VERILOG_DIR}/eq_b_i8_i8.v
${VERILOG_DIR}/fsm.v
${VERILOG_DIR}/id_b_b.v
${VERILOG_DIR}/lut_add_i8_i8_i8.v
${VERILOG_DIR}/lut_and_i8_i8_i8.v
${VERILOG_DIR}/lut_or_i8_i8_i8.v
${VERILOG_DIR}/lut_sub_i8_i8_i8.v
${VERILOG_DIR}/mux_b_b_b_b.v
${VERILOG_DIR}/mux_i8_b_i8_i8.v
${VERILOG_DIR}/nand_b_b_b.v
${VERILOG_DIR}/nand_i8_i8_i8.v
${VERILOG_DIR}/neq_b_b_b.v
${VERILOG_DIR}/neq_b_i8_i8.v
${VERILOG_DIR}/nor_b_b_b.v
${VERILOG_DIR}/not_b_b.v
${VERILOG_DIR}/or_b_b_b.v
${VERILOG_DIR}/pipeline.v
${VERILOG_DIR}/reg_i8_i8_b.v
${VERILOG_DIR}/vadd_const.v
${VERILOG_DIR}/xnor_b_b_b.v
${VERILOG_DIR}/xor_b_b_b.v
${TESTS_DIR}/test_add_i8_i8_i8.v
${TESTS_DIR}/test_sub_i8_i8_i8.v
${TESTS_DIR}/test_add_i8v4_i8v4_i8v4.v
${TESTS_DIR}/test_sub_i8v4_i8v4_i8v4.v
${TESTS_DIR}/test_add_mul_i8_i8_i8_i8.v
${TESTS_DIR}/test_add_reg_mul_i8_i8_i8_b_i8.v
${TESTS_DIR}/test_mul_i8_i8_i8.v
${TESTS_DIR}/test_and_i8_i8_i8.v
${TESTS_DIR}/test_all.v
${TESTS_DIR}/test_id_i8_i8.v
${TESTS_DIR}/test_nor_i8_i8_i8.v
${TESTS_DIR}/test_not_i8_i8.v
${TESTS_DIR}/test_or_i8_i8_i8.v
${TESTS_DIR}/test_xnor_i8_i8_i8.v
${TESTS_DIR}/test_xor_i8_i8_i8.v
${TESTS_DIR}/test_and_b_b_b.v
${TESTS_DIR}/test_const_i8.v
${TESTS_DIR}/test_dsp_add_i8_i8_i8.v
${TESTS_DIR}/test_dsp_and_i8_i8_i8.v
${TESTS_DIR}/test_dsp_or_i8_i8_i8.v
${TESTS_DIR}/test_dsp_sub_i8_i8_i8.v
${TESTS_DIR}/test_eq_b_b_b.v
${TESTS_DIR}/test_eq_b_i8_i8.v
${TESTS_DIR}/test_fsm.v
${TESTS_DIR}/test_id_b_b.v
${TESTS_DIR}/test_lut_add_i8_i8_i8.v
${TESTS_DIR}/test_lut_and_i8_i8_i8.v
${TESTS_DIR}/test_lut_or_i8_i8_i8.v
${TESTS_DIR}/test_lut_sub_i8_i8_i8.v
${TESTS_DIR}/test_mux_b_b_b_b.v
${TESTS_DIR}/test_mux_i8_b_i8_i8.v
${TESTS_DIR}/test_nand_b_b_b.v
${TESTS_DIR}/test_nand_i8_i8_i8.v
${TESTS_DIR}/test_neq_b_b_b.v
${TESTS_DIR}/test_neq_b_i8_i8.v
${TESTS_DIR}/test_nor_b_b_b.v
${TESTS_DIR}/test_not_b_b.v
${TESTS_DIR}/test_or_b_b_b.v
${TESTS_DIR}/test_pipeline.v
${TESTS_DIR}/test_reg_i8_i8_b.v
${TESTS_DIR}/test_vadd_const.v
${TESTS_DIR}/test_xnor_b_b_b.v
${TESTS_DIR}/test_xor_b_b_b.v
