${XILINX_VIVADO}/data/verilog/src/glbl.v
${VERILOG_DIR}/add_i8_i8_i8.v
${VERILOG_DIR}/sub_i8_i8_i8.v
${VERILOG_DIR}/add_i8v4_i8v4_i8v4.v
${VERILOG_DIR}/sub_i8v4_i8v4_i8v4.v
${VERILOG_DIR}/add_mul_i8_i8_i8_i8.v
${VERILOG_DIR}/add_reg_mul_i8_i8_i8_b_i8.v
${VERILOG_DIR}/mul_i8_i8_i8.v
${VERILOG_DIR}/and_i8_i8_i8.v
${VERILOG_DIR}/id_i8_i8.v
${VERILOG_DIR}/nor_i8_i8_i8.v
${VERILOG_DIR}/not_i8_i8.v
${VERILOG_DIR}/or_i8_i8_i8.v
${VERILOG_DIR}/xnor_i8_i8_i8.v
${VERILOG_DIR}/xor_i8_i8_i8.v
${TESTS_DIR}/test_add_i8_i8_i8.v
${TESTS_DIR}/test_sub_i8_i8_i8.v
${TESTS_DIR}/test_add_i8v4_i8v4_i8v4.v
${TESTS_DIR}/test_sub_i8v4_i8v4_i8v4.v
${TESTS_DIR}/test_add_mul_i8_i8_i8_i8.v
${TESTS_DIR}/test_add_reg_mul_i8_i8_i8_b_i8.v
${TESTS_DIR}/test_mul_i8_i8_i8.v
${TESTS_DIR}/test_and_i8_i8_i8.v
${TESTS_DIR}/test_all.v
${TESTS_DIR}/test_id_i8_i8.v
${TESTS_DIR}/test_nor_i8_i8_i8.v
${TESTS_DIR}/test_not_i8_i8.v
${TESTS_DIR}/test_or_i8_i8_i8.v
${TESTS_DIR}/test_xnor_i8_i8_i8.v
${TESTS_DIR}/test_xor_i8_i8_i8.v