WHITESPACE = _{ " " | "\t" | NEWLINE }

COMMENT = _{ ("//" ~ (!NEWLINE ~ ANY)* ~ NEWLINE) | "/*" ~ (!"*/" ~ ANY)* ~ "*/" }

sep = _{ "_" | "-"}

id = @{ ASCII_ALPHA+ ~ (sep | ASCII_ALPHA | ASCII_DIGIT)* }

bel = { id }

coord = { "??" | id | ASCII_DIGIT+ }

op_coord = { "+" }

expr_coord = { coord ~ (op_coord ~ coord)? }

loc = { bel? ~ "(" ~ expr_coord ~ "," ~ expr_coord ~ ")" }

file = { SOI ~ loc ~ EOI }